"""PR-5 — ``.gitignore`` must keep ``out/archive/**`` + ``search_index.json``
tracked (Git-as-DB per plan v2 §D4) while still ignoring the daily-regenerated
files under ``out/``.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parent.parent


def _check_ignore(relpath: str) -> bool:
    """Return True iff git would ignore the given (possibly non-existent) path.

    Uses ``git check-ignore`` which intentionally checks the rules without
    requiring the file to actually exist.
    """
    result = subprocess.run(
        ["git", "check-ignore", "--no-index", "--", relpath],
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
    )
    # git check-ignore returns 0 when the path matches an ignore rule,
    # 1 when no rule matches. Any other exit code is an actual error.
    if result.returncode not in (0, 1):
        pytest.skip(
            f"git check-ignore failed (rc={result.returncode}): "
            f"{result.stderr.strip()}"
        )
    return result.returncode == 0


def test_archive_not_ignored():
    assert not _check_ignore("out/archive/2026/04/19.html"), (
        "out/archive/**/*.html must be tracked (Git-as-DB persistence)"
    )
    assert not _check_ignore("out/archive/2026/04/19.json"), (
        "out/archive/**/*.json must be tracked (Git-as-DB persistence)"
    )


def test_search_index_not_ignored():
    assert not _check_ignore("out/search_index.json"), (
        "out/search_index.json must be tracked so the fallback client search "
        "works on fresh checkouts"
    )


def test_derived_outputs_ignored():
    assert _check_ignore("out/index.html"), (
        "out/index.html is rebuilt daily and must stay ignored"
    )
    assert _check_ignore("out/static/css/base.css"), (
        "out/static/** is a copy of morning_brief/site/static/ and must stay ignored"
    )
    assert _check_ignore("out/pagefind/pagefind-ui.js"), (
        "out/pagefind/** is generated by `npx pagefind` in CI and must stay ignored"
    )
